"""Authored causal decision rules for every SalesBench-100 workflow.

The provider mutation table answers *where* a supported result lands.  These
rules answer *why* a portfolio row qualifies and which independent business
facts an agent must reconcile.  They are deliberately authored per task so a
field-specific outcome cannot inherit a generic benchmark-wide explanation.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DecisionRule:
    observation_key: str
    observation_template: str
    authority_key: str
    authority_template: str
    method: str


_ROWS = """
northwind-q3-commit|buyer_procurement_evidence|{signal}; evaluation record for {account} is signed in the current period|commit_entry_control|Commit requires a buyer-confirmed procurement date plus a signed evaluation|promote to commit only when buyer timing and signed evaluation evidence agree
velora-emea-rollup|reseller_retry_fingerprint|{account} appears in retry batch {batch_id} under one immutable end-customer key|emea_rollup_control|Deduplicate retry copies before classifying the surviving opportunity from the latest permitted buyer call|collapse retry duplicates by end-customer key, then classify the surviving row as commit or upside from buyer evidence
harborstone-public-sector|award_funding_evidence|Agency evidence for {account} identifies funded milestone {milestone_id}, not vehicle access alone|public_sector_funding_control|Only an appropriated award line tied to the current performance period is funded|separate funded award milestones from speculative vehicle access and extensions
cedarline-midmarket|buyer_supported_close_date|The buyer-supported date is {close_date} after the manager bulk edit|recognized_booking_boundary|Finance permits the first compliant booking date recorded in the authority register|use the later of the buyer-supported close date and the first finance-compliant booking date
atlas-apac-currency|subscription_arr_components|Local-currency gross, excluded services, and transaction currency are recorded independently for {account}|quarter_fx_control|Use the approved {period} currency rate and nearest-whole-unit reporting convention|round((local-currency gross minus excluded services) times the approved FX rate)
lattice-partner-overlay|end_customer_identity|Gong and the partner registration identify {account} as the immutable end customer for retry group {batch_id}|forecast_credit_control|Forecast credit belongs to the legal end-customer account; reseller compensation ownership is out of scope|select the independently matched end-customer account for forecast credit without changing compensation allocation
meridian-usage-expansion|usage_validation_evidence|{account} exceeds its contracted usage band and has an identified economic buyer plus a scheduled validation call|expansion_entry_control|Usage alone is insufficient; buyer identity and a scheduled validation event are both required|move an expansion into upside only when usage, economic-buyer, and validation-call evidence all agree
opal-healthcare-commit|execution_blocker_evidence|{account} has executable signatures and the current security decision, separated from generic CRM flags|healthcare_commit_control|Certify only a quarter-end deal whose required signatures and conditional approvals are complete|distinguish real execution blockers from generic flags before certifying a healthcare commit
quarry-enterprise-split|forecast_value_components|The parent gross forecast and duplicated overlay value are separately recorded for {account}|split_credit_control|Remove the duplicated overlay from forecast value while leaving compensation allocation untouched|gross forecast value minus the duplicated overlay amount
solstice-fiscal-boundary|converted_fiscal_evidence|{close_date} maps into {period} under the approved calendar and current exit evidence|fiscal_probability_control|Booked deals are preserved; open deals use the new boundary and its approved stage-probability table|apply the new fiscal calendar first, then select the approved probability for the evidenced open stage
acorn-stalled-enterprise|unresolved_buyer_action|{signal} remains unresolved for {account}; owner attainment status is recorded separately|qbr_followup_control|Create follow-up only for an unresolved buyer action whose owner is not excluded by the quota rule|open one recovery task when the buyer action is unresolved and the owner passes the QBR exclusion control
brightwell-trial-expiry|trial_commitment_evidence|The expired trial for {account} includes a buyer-accepted technical validation date of {close_date}|trial_rescue_control|Administrative neglect qualifies only when a future validation commitment exists and no no-decision is recorded|schedule follow-up at the later of the buyer commitment and the first available technical-validation slot
cinder-manufacturing-slips|plant_timing_variance|The plant calendar moves implementation while the CRM stage for {account} remains {stage}|schedule_materiality_control|Flag only a buyer-date versus stage-plan variance beyond the documented materiality threshold|classify schedule risk from the corroborated plant-calendar variance, not repeated seller close-date edits
drift-renewal-blockers|actionable_blocker|{signal} is corroborated with current service evidence for {account}|formal_notice_exclusion|Accounts already in formal notice are excluded; each other actionable blocker receives one owned task|prioritize one recovery task per corroborated blocker while excluding formal-notice accounts
ember-champion-departures|employment_change_evidence|Contact status, bounced activity, and Gong all show the champion for {account} changed employer|relationship_rebuild_control|A rebuild action requires corroborated departure plus no active replacement relationship|record the explicit relationship-rebuild action when departure and coverage evidence agree
fable-procurement-pauses|procurement_hold_evidence|The current buyer record distinguishes explicit budget hold from silence for {account}|customer_pause_control|Documented customer-requested pauses receive no recovery task; silent actionable deals use the approved motion|classify explicit procurement holds separately from silent deals before assigning a follow-up type
granite-security-reviews|vendor_security_action|The open questionnaire item for {account} is assigned to the vendor and requires {owner_role} expertise|specialist_capacity_control|Assign the active qualified security specialist with remaining capacity, not the account executive by default|select the active security specialist whose expertise and capacity match the vendor-owned blocker
helix-multi-threading|missing_committee_role|Two permitted sources identify a missing buying-committee function for {account}|duplicate_task_control|Create stakeholder development only when that role is missing and no equivalent open task exists|develop the corroborated missing stakeholder role after excluding duplicate open work
indigo-next-step-aging|verbatim_next_step_history|The same next-step text for {account} persisted across {repeat_count} date advances with no new buyer commitment|false_freshness_control|A current-looking date is false freshness when text is repeatedly copied and Gong has no matching new commitment|mark false freshness only after comparing field-history repetition with the latest buyer commitment
juniper-partner-handoffs|handoff_ownership_evidence|Territory and partner rules identify coordinated direct and reseller ownership for {account}|handoff_scope_control|Task ownership may change; the underlying opportunity owner must remain unchanged|select qualified direct and partner task owners with capacity without reassigning the opportunity
keystone-discovery-actions|explicit_call_commitment|Permitted Gong insight records {signal} for {account} and identifies the responsible party|call_action_control|Only explicit commitments become CRM actions; private transcript text and inference are prohibited|write the explicit permitted buyer-or-seller commitment into the designated task system
lumen-exec-briefs|executive_meeting_evidence|The permitted brief for {account} contains a confirmed meeting, supported roles, and explicit follow-ups|executive_brief_control|A brief is ready only when meeting, stakeholder, and follow-up evidence all pass; speculative notes are excluded|certify executive-brief readiness from permitted meeting and stakeholder evidence
monarch-competitor-mentions|buyer_competitor_mention|Two permitted buyer-conversation sources corroborate {risk_code} for {account}|competitor_evidence_control|Marketing attribution and seller inference do not establish a competitor; explicit buyer mention does|classify competitor evidence only from independently corroborated permitted buyer mentions
nova-mutual-plans|bilateral_commitment_date|Buyer and seller both accepted the {close_date} mutual-plan milestone for {account}|mutual_plan_control|Buyer-owned items remain notes; only accepted bilateral or seller-owned commitments change CRM dates|use the later mutually accepted commitment date and applicable calendar constraint
orbit-objection-coding|active_deal_objection|Permitted account and deal insights independently support {risk_code} for active deal {account}|objection_taxonomy_control|Apply the active-deal taxonomy only; closed-lost reason governance remains out of scope|map a corroborated permitted objection to the active-deal taxonomy without touching closed-loss governance
palisade-handoff-notes|qualification_corroboration|SDR notes, call outcome, and identity evidence agree that {account} meets the current qualification gate|ae_data_boundary|Repair qualification metadata only; AE-authored commercial fields are protected|mark the handoff qualified only after SDR, Gong, and CRM evidence agree
quill-coaching-actions|customer_commitment_boundary|The call record separates explicit customer commitment {signal} from coaching-only feedback|coaching_scope_control|Customer-facing tasks require explicit commitments; coaching observations stay in the narrative output|copy the explicit permitted customer action while keeping coaching-only observations out of CRM
ridgeway-call-privacy|permitted_insight_boundary|The synthesized insight for {account} excludes private activity and raw transcript fragments|privacy_use_control|Only permitted synthesized insight may support CRM work; private-call content is never copied|certify permitted-insight-only handling after excluding private calls and transcript text
summit-commercial-terms|commercial_next_step_evidence|The permitted call insight records {signal} while legal approval remains independently unresolved|discussion_not_approval_control|Pricing discussion can establish a next step or risk, never quote approval or amount|record the explicit commercial next step without treating discussion as approval
tandem-contact-roles|stakeholder_role_evidence|Two independent permitted sources identify the role of Jordan at {account}|manual_role_control|Require two sources and preserve any manually verified opt-out|assign the corroborated buying role only when the contact is not protected by manual verification
umbra-domain-collisions|three_key_company_identity|Legal name, external ID, and Gong account reference distinguish {account} from the shared-domain subsidiary|carveout_identity_control|A shared parent domain is insufficient and the carved-out subsidiary must remain separate|mark only the company satisfying legal-name, external-ID, and Gong-reference identity controls
vector-contact-dedup|contact_identity_chain|Email history, verified employment, and external identity link resolve the contact at {account}|restrictive_consent_control|Link exact identities while preserving latest employment and the most restrictive valid consent|link only the exact contact identity and carry forward the stricter valid consent state
willow-parent-child|legal_buyer_hierarchy|External IDs and legal-buyer evidence place {account} in the approved parent-child chain|opportunity_movement_control|Restore company hierarchy without moving open opportunities between legal buyers|verify the parent-child relationship from immutable keys while preserving opportunity ownership
xenon-owner-crosswalk|active_owner_mapping|The signed crosswalk maps the active {region} record for {account} to {owner}|historical_owner_control|Apply active ownership only; historical activity owners are immutable|select the active mapped owner with capacity while preserving historical activity ownership
yellowbrick-lifecycle-sync|conversion_evidence|The identity for {account} has valid current conversion evidence rather than campaign advancement alone|converted_lead_control|Reconcile lifecycle only with conversion proof and never recreate an already converted lead|advance lifecycle status only for an exact identity with valid conversion evidence
zenith-external-id-gaps|exact_account_crosswalk|Domain, address, and legal name resolve the Salesforce and HubSpot records for {account}|ambiguous_name_control|Backfill opposite-provider IDs only for exact effective matches; quarantine name-only candidates|write the opposite provider ID from the exact effective crosswalk
alpine-acquisition-merge|acquired_identity_overlap|The acquired record for {account} matches an existing marketing identity while contracts remain legally separate|contract_preservation_control|Consolidate safe marketing identity only; contracts and Gong history remain separate|consolidate the approved marketing identity without merging protected contract records
brookfield-consent-survival|duplicate_consent_chain|Exact identity evidence for {account} exposes conflicting subscription states|strictest_valid_consent_control|The most restrictive current valid suppression survives and audit history is retained|link the exact duplicate while propagating the strictest valid consent state
cascade-custom-object-map|deployment_site_external_key|The deployment document and external key resolve the missing site association for {account}|regulated_record_control|Restore the company relationship only; regulated device records are protected|restore the site association from the exact deployment key without modifying regulated objects
delta-sandbox-cutover|production_identity_evidence|Production external IDs and current provider state certify {account}; sandbox-only aliases are separated|production_cutover_control|Only exact production identities are certified and stale sandbox references remain quarantined|certify the production identity after exact cross-system and environment matching
everest-enterprise-inbound|enterprise_fit_evidence|Firmographic and current account evidence qualify {account} for the {region} enterprise territory|named_account_capacity_control|Respect named-account ownership, active status, and remaining capacity|assign the active qualified enterprise owner after territory and capacity reconciliation
foxtrot-emea-consent|regional_consent_evidence|The current consent record and lawful-basis evidence for {account} are valid in {region}|consent_routing_control|Route only consent-eligible leads and preserve the stricter current restriction|mark routing eligibility only when the effective regional consent rule passes
ginkgo-product-led|first_party_product_signal|Authenticated usage for {account} crosses the documented product threshold and is tied to a person|anonymous_usage_control|Anonymous activity and sub-threshold usage do not qualify a handoff|qualify only a person-linked account whose first-party usage exceeds the approved threshold
highland-public-sector|ultimate_agency_identity|Agency, contractor, vehicle, and partner-origin evidence resolve the ultimate buyer for {account}|protected_account_control|Protected named accounts and valid partner registrations override default geography|centralize routing on the ultimate agency after protected-account and partner checks
ion-health-system|health_system_hierarchy|Campus form activity for {account} resolves to a centrally purchasing health-system parent|campus_preservation_control|Qualify at the parent while preserving campus contacts and route via the executive hierarchy|select the independently matched health-system parent rather than the closest campus alias
jasper-apac-capacity|language_capacity_fit|Territory and language evidence qualify {owner} for {account}|weekly_capacity_control|Choose an active qualified owner under the weekly cap; otherwise use the documented pool|select the active APAC owner satisfying territory, language, and remaining-capacity controls
kinetic-partner-sourced|registration_window_evidence|Partner registration, referral date, and existing opportunity ownership reconcile for {account}|channel_conflict_control|Choose partner, direct, or conflict review from effective protection and ownership evidence|classify the routing channel after validating registration window and existing ownership
lowell-duplicate-mqls|person_level_retry_identity|Campaign retries resolve to the same person and attribution chain at {account}|recent_disqualification_control|Consolidate duplicate routing and tasks while preserving attribution and recent disqualification|mark exact retry duplicates consolidated without erasing attribution history
mosaic-intent-threshold|named_account_intent_join|First-party engagement and third-party intent for {account} jointly cross the governed threshold|anonymous_intent_control|Anonymous-only activity cannot qualify even when the third-party surge is high|qualify only named accounts whose attributable first-party and intent scores meet the threshold
nimbus-student-exclusion|institutional_buyer_role|Identity and role evidence distinguish the institutional buyer at {account} from students and consultants|nonbuyer_analytics_control|Nonbuyers remain available to marketing analytics but receive no sales record|mark only a corroborated institutional buying persona as sales-qualified
oak-renewal-notice|controlling_notice_window|The executed contract date and current renewal date place {account} inside the cure window|missed_notice_control|Inside-window accounts receive recovery; already-missed notices follow escalation instead|classify notice status from the controlling contract window, not the stale CRM date
prairie-usage-expansion|usage_support_sentiment_join|Usage exceeds the contracted band for {account}; support severity and buyer sentiment are current|recovery_before_expansion_control|Healthy evidence permits expansion; adverse support or sentiment requires customer-success recovery|choose customer-success recovery when support and conversation evidence block a usage-led expansion
quartz-multi-product|cotermed_agreement_identity|Product opportunities for {account} share one controlling co-termed agreement ID|arr_double_count_control|Preserve line detail but assign all products to one renewal group and count ARR once|select the independently matched renewal agreement identity instead of separate product aliases
redwood-churn-save|executive_dissatisfaction_evidence|Two permitted sources corroborate executive dissatisfaction at {account} despite a green health field|churn_certainty_control|Record evidence-grounded risk and save action without declaring churn certain|classify renewal risk from corroborated executive evidence, not the stale health color
sequoia-merger-renewals|successor_billing_identity|Executed merger and billing documents resolve the successor for {account}|notice_obligation_control|Preserve contract notice obligations while choosing one coordinated active renewal owner|assign the active successor-account renewal owner with capacity and preserve contractual notices
timberline-support-risk|priority_incident_evidence|{account} has an unresolved priority incident and proposed commercial expansion|support_gate_control|Executive recovery must precede commercial follow-up while priority incidents remain open|gate expansion as recovery-required when current priority support incidents are unresolved
upland-channel-renewal|executed_end_date|Executed distributor evidence gives {close_date} as the controlling end date for {account}|compensation_scope_control|Reconcile the later valid renewal date and leave partner compensation outside scope|use the later executed end date and first policy-compliant renewal date
vista-auto-renewal|controlling_opt_out_terms|The controlling amendment for {account} requires a notice despite a generic auto-renew flag|superseding_amendment_control|Superseding negotiated terms override the base auto-renal record|require notice only when the controlling amendment and effective window establish it
watershed-seat-trueup|billable_seat_calculation|Active production seats for {account} exceed the contracted band after dormant and sandbox exclusions|trueup_candidate_control|Only billable production seats count and policy plus usage must agree|mark a true-up candidate after excluding dormant and sandbox users from the governed count
yarrow-executive-handoff|leadership_change_evidence|Current leadership evidence for {account} shows an uncovered executive sponsor role|unverified_contact_control|Create an introduction need only for a corroborated role gap; unverified contacts remain unchanged|mark executive introduction required from the corroborated leadership gap
zephyr-discount-chain|ordered_approval_evidence|Discount and TCV bands for {account} map to a complete ordered approval chain|discussion_approval_control|A Gong pricing discussion is not approval; every required approver must be recorded in order|mark quote readiness only after threshold calculation and complete ordered approvals
amber-ramp-pricing|signed_ramp_schedule|The signed annual quantities and prices for {account} reconcile across the commercial schedule|effective_discount_control|Calculate against signed ramp economics, not conflicting CRM headers|derive the effective discount from the reconciled signed ramp schedule
birch-public-sector-terms|vehicle_clause_funding_join|Mandatory clauses, vehicle access, reseller margin, and funding all reconcile for {account}|public_quote_control|A public-sector quote is ready only when every mandatory control and approval passes|certify quote readiness from vehicle, clause, margin, funding, and approval evidence
coral-nonstandard-payment|formal_finance_approval|Permitted call evidence records extended terms for {account}; formal finance approval is independently present|quote_term_protection|Classify risk and tasks only; unapproved quote terms cannot be changed|classify payment-term risk only when the offered terms and formal authorization evidence agree
dogwood-bundle-floor|sku_floor_calculation|Product-level net prices for {account} remain above their approved floors after bundle allocation|pricing_math_protection|Correct readiness only where line items and exception approvals agree; conflicting price math is untouched|test every allocated SKU against its governed floor before marking the bundle within policy
elm-partner-margin|margin_component_split|Distributor margin, end-customer discount, and quote discount are separated for {account}|genuine_exception_control|Only a component exceeding its own policy band is a partner-margin exception|classify the genuine margin exception after separating all three discount components
fir-usage-commit|normalized_commitment_value|Committed usage, variable credits, and make-good exposure are normalized for {account}|approval_band_control|Approval bands use normalized commitment value rather than headline maximum|mark approval required when normalized commitment exposure crosses the governed band
grove-currency-lock|lock_expiry_evidence|The close-date slip for {account} exceeds its currency-lock expiry and no extension is executed|formal_extension_control|Reprice expired locks; preserve locks with a formally executed extension|mark reprice only when the effective close date is later than the unextended lock expiry
hawthorn-legal-gate|open_privacy_term|The current legal register for {account} contains an unresolved privacy term despite CRM completion|executed_language_control|Legal gate stays open until executed language exists; stage and quote status are protected|reopen the legal gate from the controlling term record without changing commercial stage or quote status
ironwood-order-form|controlling_amendment_values|Order form, quote lines, and amendment sequence identify the controlling values for {account}|unsupported_discrepancy_control|Repair readiness metadata and create one task per unsupported discrepancy; amounts remain protected|mark the order-form reconciliation exception after selecting the latest controlling amendment
jade-global-account|regional_stakeholder_evidence|Two independent sources identify the regional buying role for Jordan at {account}|regional_ownership_control|Build one global map while preserving each region's ownership and verified opt-outs|assign the corroborated stakeholder role without changing regional record ownership
kingfisher-exec-map|executive_role_evidence|Two permitted sources identify Jordan's executive role and blockers at {account}|relationship_gap_control|Update supported roles and separately track uncovered functions|assign the corroborated executive role only after two-source confirmation
laurel-white-space|product_adoption_gap|Adoption and opportunity history show a qualified product gap at {account}|support_recovery_control|Open support recovery blocks outreach even when whitespace exists|mark whitespace qualified only when adoption evidence shows a gap and no recovery hold applies
maple-partner-ecosystem|partner_function_evidence|Two sources identify Jordan's consultant, integrator, or reseller function for {account}|employee_boundary_control|Partner contacts remain partners and are never converted into customer employees|assign the corroborated partner role while preserving organization type
nutmeg-contact-coverage|buying_committee_gap|Permitted themes and associations show a missing security or procurement function at {account}|person_fabrication_control|Record a role gap without inventing a person or unsupported contact|classify the corroborated coverage gap from existing associations and permitted themes
olive-support-overlay|support_adoption_risk|Current incident and adoption evidence for {account} corroborates {risk_code}|customer_fact_control|Plan risk must use support plus conversation evidence; internal battlecard claims are excluded|classify the account-plan risk from independently corroborated support and buyer evidence
pine-competitive-plan|competitive_evidence_join|CRM and permitted buyer evidence for {account} independently corroborate {risk_code}|battlecard_boundary_control|Internal-only battlecard claims cannot be represented as customer facts|classify only a competitor supported by permitted customer evidence
riverbank-succession|sponsor_departure_chain|Employment and stakeholder evidence for {account} shows responsibilities split among successors|history_preservation_control|Rebuild current relationships while preserving the departed sponsor's historical activity|mark succession rebuild required after corroborating departure and uncovered responsibilities
spruce-board-prep|operational_board_action|Permitted evidence supports {signal} as the next operational action for {account}|fact_inference_boundary|The handoff distinguishes fact, inference, and unresolved conflict; only operational facts enter CRM|record the explicit supported operational action without promoting inference to fact
topaz-regional-org|reporting_line_evidence|Country and central-procurement sources agree on Jordan's reporting line at {account}|unresolved_line_control|Restore only corroborated links and list every unresolved reporting line|mark the reporting line restored only after two-source hierarchy confirmation
umber-gdpr-sequence|lawful_basis_evidence|Enrollment, country, consent, and legitimate-interest records reconcile for {account}|prohibited_enrollment_control|Remove prohibited outreach, retain audit evidence, and create no replacement task|remove the enrollment when the effective GDPR basis does not permit continued outreach
violet-suppression-sync|strictest_suppression_state|Global and portal suppression evidence for {account} resolve to the stricter current status|transactional_scope_control|Transactional contacts outside the scoped campaign are protected|apply the strictest valid suppression to the scoped marketing enrollment
walnut-domain-health|cohort_bounce_evidence|Bounce rate for {account}'s sending-domain cohort exceeds the approved threshold|lifecycle_field_control|Pause only impacted enrollments; lifecycle fields and unaffected domains are protected|pause the affected cohort after joining domain health, sequence, and enrollment evidence
xylem-cadence-overlap|preferred_motion_evidence|The contact at {account} is active in overlapping motions with one policy-preferred sequence|completed_activity_control|Keep the preferred active motion and preserve all completed activity history|select the policy-preferred sequence and remove only the overlapping active enrollment
yucca-country-policy|effective_consent_version|Enrollment date, country, and consent revision for {account} resolve under the mid-quarter policy change|grandfathering_control|Apply the version effective on enrollment unless a stricter current restriction controls|mark the consent version current after temporal country-policy evaluation
azalea-customer-exclusion|confirmed_customer_identity|Exact company association confirms {account} is an existing customer rather than a shared-domain prospect|shared_domain_control|Remove only confirmed customers; parent-domain similarity alone is insufficient|remove acquisition outreach only for an independently matched existing customer
bluebell-reply-stop|reply_event_evidence|A delivered positive or negative reply for {account} falls inside the failed stop-integration window|completed_work_control|Cancel remaining steps and never reopen completed activity|stop the enrollment from the delivered reply event while preserving completed work
clover-event-consent|attendee_consent_join|Event scan, registration choice, and current consent for {account} agree|ambiguous_attendee_control|Enroll only fully eligible attendees and quarantine any conflicting consent record|mark event outreach eligible only when scan identity, registration, and consent agree
dahlia-role-account|mailbox_person_identity|Mailbox evidence for {account} distinguishes a personal opted-in buyer from a generic role account|duplicate_person_control|Remove generic mailboxes and duplicates while retaining valid opted-in people|remove outreach when the independently classified mailbox is non-personal or duplicate
eucalyptus-frequency-cap|weekly_contact_count|Cross-team contact count for {account} exceeds the governed weekly cap|motion_priority_control|Preserve the highest-priority active motion and stop only excess enrollments|pause excess outreach after counting the week and selecting the policy-priority motion
fjord-phase-one-cutover|approved_source_key|The frozen manifest supplies an approved association key for {account}|missing_key_quarantine|Restore deterministic associations only; rows without approved keys are quarantined|restore the missing association from the exact approved cutover key
glacier-stage-map|conditional_stage_evidence|Probability, exit evidence, and closed status for {account} satisfy one approved mapping branch|closed_status_control|Reapply the conditional mapping without reopening closed records|select the mapped stage from probability, exit evidence, and closed-state conditions
hemlock-owner-migration|signed_owner_crosswalk|The signed restructuring crosswalk maps active {account} ownership to {owner}|historical_activity_control|Repair active records only and preserve historical activity owners|select the active mapped owner with capacity from the signed crosswalk
isotope-activity-counts|allowed_activity_count|Public CRM activities for {account} reconcile after archived engagement rules and private-call exclusions|private_activity_control|Archived handling follows the acceptance rule and private Gong calls never count|mark activity counts reconciled from permitted current and archived records only
kestrel-line-item-cutover|frozen_line_item_manifest|The frozen manifest identifies the missing line-item association and source value for {account}|pricing_protection_control|Restore supported association and value without recalculating or changing price|mark the line-item migration restored from the immutable manifest
lagoon-consent-cutover|purpose_timestamp_consent|Purpose, timestamp, and source category for {account} resolve to the stricter valid state|audit_evidence_control|Map by purpose and time, favor restriction, and retain source evidence|mark migrated consent restricted when it is the stricter valid mapped state
meadow-gong-linkage|retired_opportunity_crosswalk|The effective mapping links retired and current opportunity IDs for {account}|gong_readonly_control|Repair CRM-side external links and context only; Gong remains read-only|write the opposite provider ID from the exact effective crosswalk
northstar-custom-fields|risk_field_mapping_evidence|Source risk and regulatory values for {account} satisfy the approved transformation rule|regulated_acceptance_control|Correct only exact mappings and place all conflicts in the exception register|mark the migrated risk field accepted only when source and mapping evidence agree
orchard-delta-load|freeze_window_event_identity|Timestamp and external ID show the {account} event was duplicated or omitted during replay|post_cutover_edit_control|Remove deterministic replay defects while preserving legitimate post-cutover edits|mark the delta load reconciled after event-identity and freeze-window comparison
pebble-rollback-readiness|acceptance_exception_join|Record, owner, activity, and Gong-link exceptions for {account} are all resolved in scope|rollback_manifest_control|Acceptance requires every mandatory class to pass; unresolved rows remain in rollback manifest|clear rollback exception status only after all mandatory acceptance classes reconcile
""".strip()


def _parse_rows() -> dict[str, DecisionRule]:
    rules: dict[str, DecisionRule] = {}
    for line_number, line in enumerate(_ROWS.splitlines(), start=1):
        fields = [field.strip() for field in line.split("|")]
        if len(fields) != 6:
            raise ValueError(
                f"decision rule line {line_number} has {len(fields)} fields, expected 6"
            )
        slug, observation_key, observation, authority_key, authority, method = fields
        if slug in rules:
            raise ValueError(f"duplicate decision rule for {slug}")
        rules[slug] = DecisionRule(
            observation_key=observation_key,
            observation_template=observation,
            authority_key=authority_key,
            authority_template=authority,
            method=method,
        )
    if len(rules) != 100:
        raise ValueError(f"expected 100 decision rules, found {len(rules)}")
    return rules


DECISION_RULES = _parse_rows()


def validate_decision_rules(slugs: set[str]) -> None:
    missing = slugs - set(DECISION_RULES)
    extra = set(DECISION_RULES) - slugs
    if missing or extra:
        raise ValueError(
            f"decision rule mismatch: missing={sorted(missing)}, extra={sorted(extra)}"
        )
